### ISSUE TITLE
New forms should not show error state by default

### ISSUE THREAD

**Issue by jeremydw** [blinkk/selective-edit#44]
The red text makes it look like the user did something wrong, it shouldn't show an error until the user has tried to submit it and it is not valid.

![image](https://user-images.githubusercontent.com/646525/126734293-e663b800-8958-4f51-87c5-96134d483913.png)

**Comment by adelaidemt** [comment]
Todo:
- research precedent for errors from contentful / other CMS tools 
- design a "required field" message 
- enabled button instead of disabled button

**Comment by Zoramite** [comment]
Initial UI changes being implemented:

- Add a `*` to required field's label
- Track each field to know if it has been focused. When a field has lost focus allow the error messages to show. This makes it so it doesn't show the errors until after the user has 'left' the field.
- Track when the form was 'submitted'. This will enable the submit button until they try to submit then disable until the errors are fixed.

I think these general changes should handle most of the bad UX for forms. @micjamking if you have any other design changes that you want for showing required fields let me know.
