### ISSUE TITLE
Add numbers to repeated sections/list items 

### ISSUE THREAD

**Issue by adelaidemt** [blinkk/selective-edit#54]
It would be good to have repeated list items show numbers, so we can easily reference them without adding names to each file. Example of this in practice is the multiple image carousels within the product pages just using "Slide": 

![images](https://user-images.githubusercontent.com/24655972/128235932-2073bfc7-9e2d-4823-a365-0843ed4d0f61.png)

**Comment by Zoramite** [comment]
Closed by #53
